schema: storefront.schema.json
documents:
  - "lib/**/*.{ts,tsx}"
  - "app/**/*.{ts,tsx}"
  - "components/**/*.{ts,tsx}"
  - "hooks/**/*.{ts,tsx}"
  - "contexts/**/*.{ts,tsx}"
  - "services/**/*.{ts,tsx}"
